#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

"""Settings of the FreeRADIUS module that do not belong in the environment.

state/environment is mirrored to Redis in plain text, so everything that
contains a secret (the shared secrets of the RADIUS clients) is kept in JSON
files with mode 0600 inside the state directory. The files in
state/generated/ are rebuilt from them before every start of the server.
"""

import ipaddress
import json
import os
import re

CLIENTS_FILE = "clients.json"
GENERATED_DIR = "generated"

NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,62}$")
# printable ASCII without double quote and backslash: the value is written
# inside a double quoted string of clients.conf
SECRET_RE = re.compile(r'^[\x20-\x21\x23-\x5b\x5d-\x7e]{8,128}$')


def _write_private(path, content):
    tmp = f"{path}.{os.getpid()}.tmp"
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as fp:
        fp.write(content)
    os.replace(tmp, path)


def read_clients():
    try:
        with open(CLIENTS_FILE) as fp:
            return json.load(fp)
    except FileNotFoundError:
        return []


def write_clients(clients):
    _write_private(CLIENTS_FILE, json.dumps(clients, indent=2) + "\n")


def validate_clients(clients):
    """Return a list of validation errors in the format of the NS8 UI."""
    errors = []
    names = set()
    for idx, client in enumerate(clients):
        field = f"clients.{idx}"
        name = client.get("name", "")
        if not NAME_RE.match(name):
            errors.append({"field": field, "parameter": "clients", "value": name, "error": "client_name_invalid"})
        elif name.lower() in names:
            errors.append({"field": field, "parameter": "clients", "value": name, "error": "client_name_duplicate"})
        names.add(name.lower())
        try:
            ipaddress.ip_network(client.get("ipaddr", ""), strict=False)
        except ValueError:
            errors.append({"field": field, "parameter": "clients", "value": client.get("ipaddr", ""), "error": "client_ipaddr_invalid"})
        if not SECRET_RE.match(client.get("secret", "")):
            # never echo a secret back in an error message
            errors.append({"field": field, "parameter": "clients", "value": name, "error": "client_secret_invalid"})
    return errors


def quote(value):
    """Return value as a double-quoted FreeRADIUS string (backslash and quote escaped)."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_clients_conf(clients):
    out = [
        "# Generated by the module from the clients set in the UI/API: do not edit.",
        "# Clients added by hand belong in state/config/clients.conf, included below.",
        "",
    ]
    for client in clients:
        net = ipaddress.ip_network(client["ipaddr"], strict=False)
        out += [
            f"client {client['name']} {{",
            f"\t{'ipv6addr' if net.version == 6 else 'ipaddr'} = {net.with_prefixlen}",
            f"\tsecret = {quote(client['secret'])}",
            "}",
            "",
        ]
    out += ["$INCLUDE clients.custom.conf", ""]
    return "\n".join(out)


def _template(name):
    with open(os.path.join(os.environ["AGENT_INSTALL_DIR"], "templates", name)) as fp:
        return fp.read()


def expand():
    os.makedirs(GENERATED_DIR, mode=0o700, exist_ok=True)
    _write_private(os.path.join(GENERATED_DIR, "eap"), _template("eap"))
    _write_private(os.path.join(GENERATED_DIR, "clients.conf"), render_clients_conf(read_clients()))
