#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Traefik obtained, renewed or received a certificate: if it is the one of
# our host name, fetch it and restart the server so that EAP uses it
# (FreeRADIUS reads certificates at start only).

import json
import os
import sys

import agent

event = json.load(sys.stdin)
myname = os.environ.get("TRAEFIK_HOST", "")

if not myname or not agent.certificate_event_matches(event, myname):
    sys.exit(0)

get_proc = agent.run_helper('get-certificate', '--cert-file=certs/server.pem', '--key-file=certs/server.key', myname)
if get_proc.returncode == 0:
    agent.run_helper('systemctl', '--user', '-T', 'try-restart', 'freeradius-app.service')
